version: '3.8'

services:
  backend:
    build: ./emplacement-backend-api
    ports:
      - 8080:8080
    depends_on:
      - frontend
  bot:
    build : ./telegram-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - frontend
      - backend
  frontend:
    build: ./client
    ports:
      - 8009:80