version: '3.8'

services:

  bot:
    build : ./telegrambot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
  backend:
    build: ./emplacement-backend-api
    ports:
      - 8080:8080
    depends_on:
      - bot
      - frontend
  frontend:
    build: ./client
    ports:
      - 8011:8011